[package]
name = "knukki"
version = "0.1.0"
authors = ["knokko <knokogator@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

provider = ["glutin", "glow"]

[dependencies]
golem = "0.1.7"

glutin = { version = "0.22.0", optional = true }
glow = { version = "0.4.0", optional = true }