[package]
name = "knukki"
version = "0.1.0"
authors = ["knokko <knokogator@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
golem_rendering = ["golem"]
provider = ["glutin", "glow"]

[[example]]
name = "color_clicking"
required-features = ["golem_rendering", "provider"]

[[example]]
name = "color_clicking_menu"
required-features = ["golem_rendering", "provider"]

[[example]]
name = "color_changing_rect"
required-features = ["golem_rendering", "provider"]

[[example]]
name = "partial_color_changing_rect"
required-features = ["golem_rendering", "provider"]

[dependencies]
golem = { path = "../golem", optional = true }
glutin = { version = "0.22.0", optional = true }
glow = { version = "0.4.0", optional = true }