#!/bin/sh

wasm-pack build examples/$1 --target web --out-name web --out-dir ../../pkg

cargo install basic-http-server
xdg-open http://0.0.0.0:4000/pkg/ || start "" http://localhost:4000/pkg/
basic-http-server .